seed: 42
data_dir: data
processed_dir: data/processed
raw_dir: data/raw
tour: both  # 'atp' | 'wta' | 'both'
include_market_features: false  # can toggle true later
exclude_retirements: true
surface_list: ["Hard", "Clay", "Grass"]
indoor_flag: true
calibrator: "auto"  # "auto" chooses isotonic vs platt by validation

sources:
  sackmann_atp: external/tennis_atp
  sackmann_wta: external/tennis_wta
  tml_db: external/TML-Database
  tcb: external/tennis-crystal-ball

use_markets_as_features: false
